fix: add missing support for "readScriptOptions"
violentmonkey/violentmonkey pull request #1257
Opened 2021-04-18 09:55 UTC by 22-2

Probably related to #1253

2021-04-18 10:39 UTC, gera2ld commented on src/options/views/tab-settings/vm-import.vue
> +            || more.props.lastModified // Import data from Tampermonkey
`more.props` would not exist when importing from a Violentmonkey export. You can use optional chaining (`?.`) here.

2021-04-18 10:42 UTC, gera2ld requested changes

2021-04-18 10:42 UTC, gera2ld commented on src/options/views/tab-settings/vm-import.vue
> +            || more.props.lastModified // Import data from Tampermonkey
`more.props` would not exist when importing from a Violentmonkey export. You can use optional chaining (`?.`) here.

2021-04-18 13:26 UTC, gera2ld requested changes

2021-04-18 13:26 UTC, gera2ld commented on src/options/views/tab-settings/vm-import.vue
> +            || more?.props.lastModified // Import data from Tampermonkey
It should be `more.props?.lastModified` since `more` always exists but `more.props` may be undefined.

2021-04-18 16:05 UTC, gera2ld approved these changes

2021-04-18 17:07 UTC, 22-2 commented
Thank you for reviewing and approving this!

2021-04-19 02:27 UTC, merged

2021-04-19 02:27 UTC, gera2ld commented
Thanks for the PR 😃