`browserAction.setIcon` by `path` only
violentmonkey/violentmonkey pull request #1971
Opened 2023-12-02 11:11 UTC by cyfung1031

see #1939

2023-12-02 11:14 UTC, tophf requested changes
As the comment for `iconDataCache` says caching is necessary.

2023-12-02 11:21 UTC, tophf commented
Here's the comment:

> Caching own icon to improve dashboard loading speed, as well as browserAction API
> (e.g. Chrome wastes 40ms in our extension's process to read 4 icons for every tab).

2023-12-02 11:29 UTC, cyfung1031 commented
> Here's the comment:
> 
> > Caching own icon to improve dashboard loading speed, as well as browserAction API
> > (e.g. Chrome wastes 40ms in our extension's process to read 4 icons for every tab).

OK. Can I make a boolean like "isOrion" then bypass the imageData and just pass the filepath for Orion?

2023-12-02 11:30 UTC, tophf commented
Ideally, the bug should be reported to Orion makers so if they fix it there'll be no need for kludges.

2023-12-02 12:06 UTC, tophf commented on src/common/safe-globals.js
> +export const IS_ORION = typeof webkitIndexedDB === 'object' && chrome.contentScripts && !navigator.userAgentData;
This may change suddenly in th next version of Orion...

2023-12-07 17:37 UTC, tophf commented
So they say they'll fix this bug, which means there's no need for IS_ORION, assuming people use the latest version, which should be the case normally.

2023-12-07 17:37 UTC, closed without merging